pipeline:
  identifier: Build_techwitzs_ventures_agros_webapp_1722593994659
  name: Agros Webapp
  orgIdentifier: default
  projectIdentifier: AgrosHub_App
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1722593944019
        repoName: techwitzs-ventures/agros-webapp
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: build
                  name: build
                  spec:
                    command: npm run build
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
  tags: {}
