/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cloud_logic_custom": [
        {
            "name": "techwitzsapi",
            "endpoint": "https://qfmah3idx0.execute-api.ap-southeast-1.amazonaws.com/develop",
            "region": "ap-southeast-1"
        }
    ],
    "aws_cognito_identity_pool_id": "ap-southeast-1:0ddc9a90-581e-435f-8436-447aa4797d87",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_wiEgYhzH0",
    "aws_user_pools_web_client_id": "19ha8mmhb4oh3vp4vfr8l1nnie",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "PHONE_NUMBER"
    ],
    "aws_dynamodb_all_tables_region": "ap-southeast-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "invoice-develop",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "itemscategory-develop",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "items-develop",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "itemswishlist-develop",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "maxdata-develop",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "purchaseorder-develop",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "salesorder-develop",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "tenant-develop",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "user-develop",
            "region": "ap-southeast-1"
        }
    ]
};


export default awsmobile;
