/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cloud_logic_custom": [
        {
            "name": "techwitzsapi",
            "endpoint": "https://85dciimtl9.execute-api.ap-southeast-1.amazonaws.com/staging",
            "region": "ap-southeast-1"
        }
    ],
    "aws_cognito_identity_pool_id": "ap-southeast-1:a61fe306-8a99-4a2c-a6e5-37e993d384e2",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_A45jk8Jgh",
    "aws_user_pools_web_client_id": "3qmvk0o7hb8jm7air3so6s6cdj",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "PHONE_NUMBER"
    ],
    "aws_dynamodb_all_tables_region": "ap-southeast-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "invoice-staging",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "itemscategory-staging",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "items-staging",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "itemswishlist-staging",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "maxdata-staging",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "purchaseorder-staging",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "salesorder-staging",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "tenant-staging",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "user-staging",
            "region": "ap-southeast-1"
        }
    ]
};


export default awsmobile;
