/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cloud_logic_custom": [
        {
            "name": "techwitzsapi",
            "endpoint": "https://16zvbdtna2.execute-api.ap-southeast-1.amazonaws.com/production",
            "region": "ap-southeast-1"
        }
    ],
    "aws_cognito_identity_pool_id": "ap-southeast-1:6a48d3f5-ec17-4040-b67e-ccc643ceee76",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_gysDqT3jh",
    "aws_user_pools_web_client_id": "69opi6k6fo456morolehln3i8t",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "PHONE_NUMBER"
    ],
    "aws_dynamodb_all_tables_region": "ap-southeast-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "invoice-production",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "itemscategory-production",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "items-production",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "itemswishlist-production",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "maxdata-production",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "purchaseorder-production",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "salesorder-production",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "tenant-production",
            "region": "ap-southeast-1"
        },
        {
            "tableName": "user-production",
            "region": "ap-southeast-1"
        }
    ]
};


export default awsmobile;
